export const mockProducts = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    price: 299.99,
    originalPrice: 399.99,
    image: "/premium-wireless-headphones.png",
    rating: 4.8,
    reviews: 234,
    category: "electronics",
    badge: "Trending",
  },
  {
    id: "2",
    name: "Designer Leather Handbag",
    price: 549.99,
    image: "/luxury-leather-handbag.jpg",
    rating: 4.9,
    reviews: 189,
    category: "fashion",
  },
  {
    id: "3",
    name: "Smart Watch Pro",
    price: 399.99,
    originalPrice: 499.99,
    image: "/modern-smart-watch.jpg",
    rating: 4.7,
    reviews: 456,
    category: "electronics",
    badge: "Best Seller",
  },
  {
    id: "4",
    name: "Minimalist Desk Lamp",
    price: 89.99,
    image: "/modern-minimalist-desk-lamp.jpg",
    rating: 4.6,
    reviews: 123,
    category: "home",
  },
  {
    id: "5",
    name: "Organic Cotton T-Shirt",
    price: 49.99,
    originalPrice: 69.99,
    image: "/premium-cotton-tshirt.jpg",
    rating: 4.5,
    reviews: 567,
    category: "fashion",
  },
  {
    id: "6",
    name: "Ceramic Coffee Mug Set",
    price: 39.99,
    image: "/elegant-ceramic-coffee-mugs.jpg",
    rating: 4.8,
    reviews: 234,
    category: "home",
  },
  {
    id: "7",
    name: "Wireless Charging Pad",
    price: 59.99,
    image: "/sleek-wireless-charger.jpg",
    rating: 4.7,
    reviews: 345,
    category: "electronics",
  },
  {
    id: "8",
    name: "Luxury Scented Candle",
    price: 34.99,
    image: "/luxury-scented-candle.jpg",
    rating: 4.9,
    reviews: 178,
    category: "home",
  },
  {
    id: "9",
    name: "Leather Wallet",
    price: 79.99,
    image: "/leather-wallet.jpg",
    rating: 4.6,
    reviews: 289,
    category: "accessories",
  },
  {
    id: "10",
    name: "Bluetooth Speaker",
    price: 149.99,
    originalPrice: 199.99,
    image: "/bluetooth-speaker.jpg",
    rating: 4.8,
    reviews: 412,
    category: "electronics",
  },
  {
    id: "11",
    name: "Silk Scarf",
    price: 89.99,
    image: "/flowing-silk-scarf.png",
    rating: 4.7,
    reviews: 156,
    category: "fashion",
  },
  {
    id: "12",
    name: "Yoga Mat Premium",
    price: 69.99,
    image: "/rolled-yoga-mat.png",
    rating: 4.5,
    reviews: 234,
    category: "accessories",
  },
  {
    id: "13",
    name: "Stainless Steel Water Bottle",
    price: 29.99,
    image: "/reusable-water-bottle.png",
    rating: 4.8,
    reviews: 567,
    category: "accessories",
  },
  {
    id: "14",
    name: "Decorative Throw Pillow",
    price: 44.99,
    image: "/decorative-throw-pillows.png",
    rating: 4.6,
    reviews: 198,
    category: "home",
  },
  {
    id: "15",
    name: "Sunglasses Classic",
    price: 159.99,
    originalPrice: 219.99,
    image: "/stylish-sunglasses.png",
    rating: 4.9,
    reviews: 345,
    category: "accessories",
  },
  {
    id: "16",
    name: "Laptop Sleeve",
    price: 39.99,
    image: "/laptop-sleeve.png",
    rating: 4.7,
    reviews: 289,
    category: "electronics",
  },
] as const
